/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DateOnlyDTO } from '../model/models';
import { DateOnlyDTOJsonAPIResponse } from '../model/models';
import { DateOnlyJsonAPIResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DateOnlyEchoServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    apiV1DateOnlyGet(extraHttpRequestParams?: any): Observable<DateOnlyJsonAPIResponse>;

    /**
     * 
     * 
     * @param dateOnlyDTO 
     */
    apiV1DateOnlyPost(dateOnlyDTO?: DateOnlyDTO, extraHttpRequestParams?: any): Observable<DateOnlyDTOJsonAPIResponse>;

}
