/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PensionStatusDTOAPIResponse } from '../model/models';
import { PensionStatusEntryDTO } from '../model/models';
import { PensionStatusEntryDTOAPIResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PensionPPOStatusServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param ppoId 
     * @param statusFlag 
     */
    apiV1PpoPpoIdStatusStatusFlagDelete(ppoId: number, statusFlag: number, extraHttpRequestParams?: any): Observable<PensionStatusDTOAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     * @param statusFlag 
     */
    apiV1PpoPpoIdStatusStatusFlagGet(ppoId: number, statusFlag: number, extraHttpRequestParams?: any): Observable<PensionStatusDTOAPIResponse>;

    /**
     * 
     * 
     * @param pensionStatusEntryDTO 
     */
    apiV1PpoStatusPost(pensionStatusEntryDTO?: PensionStatusEntryDTO, extraHttpRequestParams?: any): Observable<PensionStatusEntryDTOAPIResponse>;

}
