/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DynamicListQueryParameters } from '../model/models';
import { PensionCategoryEntryDTO } from '../model/models';
import { PensionCategoryListDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { PensionCategoryResponseDTOJsonAPIResponse } from '../model/models';
import { PensionPrimaryCategoryEntryDTO } from '../model/models';
import { PensionPrimaryCategoryResponseDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { PensionPrimaryCategoryResponseDTOJsonAPIResponse } from '../model/models';
import { PensionSubCategoryEntryDTO } from '../model/models';
import { PensionSubCategoryResponseDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { PensionSubCategoryResponseDTOJsonAPIResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PensionCategoryMasterServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PensionCategoryPatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<PensionCategoryListDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param pensionCategoryEntryDTO 
     */
    apiV1PensionCategoryPost(pensionCategoryEntryDTO?: PensionCategoryEntryDTO, extraHttpRequestParams?: any): Observable<PensionCategoryResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PensionPrimaryCategoryPatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<PensionPrimaryCategoryResponseDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param pensionPrimaryCategoryEntryDTO 
     */
    apiV1PensionPrimaryCategoryPost(pensionPrimaryCategoryEntryDTO?: PensionPrimaryCategoryEntryDTO, extraHttpRequestParams?: any): Observable<PensionPrimaryCategoryResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PensionSubCategoryPatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<PensionSubCategoryResponseDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param pensionSubCategoryEntryDTO 
     */
    apiV1PensionSubCategoryPost(pensionSubCategoryEntryDTO?: PensionSubCategoryEntryDTO, extraHttpRequestParams?: any): Observable<PensionSubCategoryResponseDTOJsonAPIResponse>;

}
