/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { InitiateFirstPensionBillDTO } from '../model/models';
import { InitiateFirstPensionBillResponseDTOJsonAPIResponse } from '../model/models';
import { PensionerFirstBillResponseDTOJsonAPIResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PensionFirstBillServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param initiateFirstPensionBillDTO 
     */
    apiV1PpoPensionBillPatch(initiateFirstPensionBillDTO?: InitiateFirstPensionBillDTO, extraHttpRequestParams?: any): Observable<InitiateFirstPensionBillResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     */
    apiV1PpoPpoIdFirstBillGeneralPost(ppoId: number, extraHttpRequestParams?: any): Observable<PensionerFirstBillResponseDTOJsonAPIResponse>;

}
