/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DynamicListQueryParameters } from '../model/models';
import { PensionBreakupEntryDTO } from '../model/models';
import { PensionBreakupResponseDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { PensionBreakupResponseDTOJsonAPIResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PensionComponentServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PensionBillComponentPatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<PensionBreakupResponseDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param pensionBreakupEntryDTO 
     */
    apiV1PensionBillComponentPost(pensionBreakupEntryDTO?: PensionBreakupEntryDTO, extraHttpRequestParams?: any): Observable<PensionBreakupResponseDTOJsonAPIResponse>;

}
