/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DynamicListQueryParameters } from '../model/models';
import { PensionerEntryDTO } from '../model/models';
import { PensionerListItemDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { PensionerResponseDTOAPIResponse } from '../model/models';
import { PensionerResponseDTOJsonAPIResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PensionPPODetailsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PpoDetailsPatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<PensionerListItemDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param pensionerEntryDTO 
     */
    apiV1PpoDetailsPost(pensionerEntryDTO?: PensionerEntryDTO, extraHttpRequestParams?: any): Observable<PensionerResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     */
    apiV1PpoPpoIdDetailsGet(ppoId: number, extraHttpRequestParams?: any): Observable<PensionerResponseDTOAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     * @param pensionerEntryDTO 
     */
    apiV1PpoPpoIdDetailsPut(ppoId: number, pensionerEntryDTO?: PensionerEntryDTO, extraHttpRequestParams?: any): Observable<PensionerResponseDTOAPIResponse>;

}
