/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ComponentRateEntryDTO } from '../model/models';
import { ComponentRateResponseDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { ComponentRateResponseDTOJsonAPIResponse } from '../model/models';
import { DynamicListQueryParameters } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PensionComponentRateServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PensionComponentRatePatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<ComponentRateResponseDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param componentRateEntryDTO 
     */
    apiV1PensionComponentRatePost(componentRateEntryDTO?: ComponentRateEntryDTO, extraHttpRequestParams?: any): Observable<ComponentRateResponseDTOJsonAPIResponse>;

}
