/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PensionerBankAcDTO } from '../model/models';
import { PensionerBankAcDTOAPIResponse } from '../model/models';
import { PensionerBankAcDTOJsonAPIResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PensionBankAccountsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param ppoId 
     */
    apiV1PpoPpoIdBankAccountsGet(ppoId: number, extraHttpRequestParams?: any): Observable<PensionerBankAcDTOAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     * @param pensionerBankAcDTO 
     */
    apiV1PpoPpoIdBankAccountsPost(ppoId: number, pensionerBankAcDTO?: PensionerBankAcDTO, extraHttpRequestParams?: any): Observable<PensionerBankAcDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     * @param pensionerBankAcDTO 
     */
    apiV1PpoPpoIdBankAccountsPut(ppoId: number, pensionerBankAcDTO?: PensionerBankAcDTO, extraHttpRequestParams?: any): Observable<PensionerBankAcDTOAPIResponse>;

}
