/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DynamicListQueryParameters } from '../model/models';
import { ListAllPpoReceiptsResponseDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { ManualPpoReceiptEntryDTO } from '../model/models';
import { ManualPpoReceiptResponseDTOAPIResponse } from '../model/models';
import { ManualPpoReceiptResponseDTOJsonAPIResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PensionManualPPOReceiptServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1ManualPpoReceiptsPatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<ListAllPpoReceiptsResponseDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param manualPpoReceiptEntryDTO 
     */
    apiV1ManualPpoReceiptsPost(manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO, extraHttpRequestParams?: any): Observable<ManualPpoReceiptResponseDTOAPIResponse>;

    /**
     * 
     * 
     * @param treasuryReceiptNo 
     */
    apiV1ManualPpoReceiptsTreasuryReceiptNoGet(treasuryReceiptNo: string, extraHttpRequestParams?: any): Observable<ManualPpoReceiptResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param treasuryReceiptNo 
     * @param manualPpoReceiptEntryDTO 
     */
    apiV1ManualPpoReceiptsTreasuryReceiptNoPut(treasuryReceiptNo: string, manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO, extraHttpRequestParams?: any): Observable<ManualPpoReceiptResponseDTOJsonAPIResponse>;

}
