/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ComponentRateEntryDTO } from '../model/models';
import { ComponentRateResponseDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { ComponentRateResponseDTOJsonAPIResponse } from '../model/models';
import { DateOnlyDTO } from '../model/models';
import { DateOnlyDTOJsonAPIResponse } from '../model/models';
import { DateOnlyJsonAPIResponse } from '../model/models';
import { DynamicListQueryParameters } from '../model/models';
import { InitiateFirstPensionBillDTO } from '../model/models';
import { InitiateFirstPensionBillResponseDTOJsonAPIResponse } from '../model/models';
import { ListAllPpoReceiptsResponseDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { ManualPpoReceiptEntryDTO } from '../model/models';
import { ManualPpoReceiptResponseDTOAPIResponse } from '../model/models';
import { ManualPpoReceiptResponseDTOJsonAPIResponse } from '../model/models';
import { ObjectJsonAPIResponse } from '../model/models';
import { PensionBreakupEntryDTO } from '../model/models';
import { PensionBreakupResponseDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { PensionBreakupResponseDTOJsonAPIResponse } from '../model/models';
import { PensionCategoryEntryDTO } from '../model/models';
import { PensionCategoryListDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { PensionCategoryResponseDTOJsonAPIResponse } from '../model/models';
import { PensionPrimaryCategoryEntryDTO } from '../model/models';
import { PensionPrimaryCategoryResponseDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { PensionPrimaryCategoryResponseDTOJsonAPIResponse } from '../model/models';
import { PensionStatusDTOAPIResponse } from '../model/models';
import { PensionStatusEntryDTO } from '../model/models';
import { PensionStatusEntryDTOAPIResponse } from '../model/models';
import { PensionSubCategoryEntryDTO } from '../model/models';
import { PensionSubCategoryResponseDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { PensionSubCategoryResponseDTOJsonAPIResponse } from '../model/models';
import { PensionerBankAcDTO } from '../model/models';
import { PensionerBankAcDTOAPIResponse } from '../model/models';
import { PensionerBankAcDTOJsonAPIResponse } from '../model/models';
import { PensionerEntryDTO } from '../model/models';
import { PensionerFirstBillResponseDTOJsonAPIResponse } from '../model/models';
import { PensionerListItemDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { PensionerResponseDTOAPIResponse } from '../model/models';
import { PensionerResponseDTOJsonAPIResponse } from '../model/models';
import { PpoComponentRateEntryDTO } from '../model/models';
import { PpoComponentRateResponseDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { PpoComponentRateResponseDTOJsonAPIResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PensionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    apiV1DateOnlyGet(extraHttpRequestParams?: any): Observable<DateOnlyJsonAPIResponse>;

    /**
     * 
     * 
     * @param dateOnlyDTO 
     */
    apiV1DateOnlyPost(dateOnlyDTO?: DateOnlyDTO, extraHttpRequestParams?: any): Observable<DateOnlyDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param body 
     */
    apiV1EchoPost(body?: any, extraHttpRequestParams?: any): Observable<ObjectJsonAPIResponse>;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1ManualPpoReceiptsPatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<ListAllPpoReceiptsResponseDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param manualPpoReceiptEntryDTO 
     */
    apiV1ManualPpoReceiptsPost(manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO, extraHttpRequestParams?: any): Observable<ManualPpoReceiptResponseDTOAPIResponse>;

    /**
     * 
     * 
     * @param treasuryReceiptNo 
     */
    apiV1ManualPpoReceiptsTreasuryReceiptNoGet(treasuryReceiptNo: string, extraHttpRequestParams?: any): Observable<ManualPpoReceiptResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param treasuryReceiptNo 
     * @param manualPpoReceiptEntryDTO 
     */
    apiV1ManualPpoReceiptsTreasuryReceiptNoPut(treasuryReceiptNo: string, manualPpoReceiptEntryDTO?: ManualPpoReceiptEntryDTO, extraHttpRequestParams?: any): Observable<ManualPpoReceiptResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PensionBillComponentPatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<PensionBreakupResponseDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param pensionBreakupEntryDTO 
     */
    apiV1PensionBillComponentPost(pensionBreakupEntryDTO?: PensionBreakupEntryDTO, extraHttpRequestParams?: any): Observable<PensionBreakupResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PensionCategoryPatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<PensionCategoryListDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param pensionCategoryEntryDTO 
     */
    apiV1PensionCategoryPost(pensionCategoryEntryDTO?: PensionCategoryEntryDTO, extraHttpRequestParams?: any): Observable<PensionCategoryResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PensionComponentRatePatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<ComponentRateResponseDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param componentRateEntryDTO 
     */
    apiV1PensionComponentRatePost(componentRateEntryDTO?: ComponentRateEntryDTO, extraHttpRequestParams?: any): Observable<ComponentRateResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PensionPrimaryCategoryPatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<PensionPrimaryCategoryResponseDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param pensionPrimaryCategoryEntryDTO 
     */
    apiV1PensionPrimaryCategoryPost(pensionPrimaryCategoryEntryDTO?: PensionPrimaryCategoryEntryDTO, extraHttpRequestParams?: any): Observable<PensionPrimaryCategoryResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PensionSubCategoryPatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<PensionSubCategoryResponseDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param pensionSubCategoryEntryDTO 
     */
    apiV1PensionSubCategoryPost(pensionSubCategoryEntryDTO?: PensionSubCategoryEntryDTO, extraHttpRequestParams?: any): Observable<PensionSubCategoryResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PpoComponentRatePatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<PpoComponentRateResponseDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param ppoComponentRateEntryDTO 
     */
    apiV1PpoComponentRatePost(ppoComponentRateEntryDTO?: PpoComponentRateEntryDTO, extraHttpRequestParams?: any): Observable<PpoComponentRateResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PpoDetailsPatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<PensionerListItemDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param pensionerEntryDTO 
     */
    apiV1PpoDetailsPost(pensionerEntryDTO?: PensionerEntryDTO, extraHttpRequestParams?: any): Observable<PensionerResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param initiateFirstPensionBillDTO 
     */
    apiV1PpoPensionBillPatch(initiateFirstPensionBillDTO?: InitiateFirstPensionBillDTO, extraHttpRequestParams?: any): Observable<InitiateFirstPensionBillResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     */
    apiV1PpoPpoIdBankAccountsGet(ppoId: number, extraHttpRequestParams?: any): Observable<PensionerBankAcDTOAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     * @param pensionerBankAcDTO 
     */
    apiV1PpoPpoIdBankAccountsPost(ppoId: number, pensionerBankAcDTO?: PensionerBankAcDTO, extraHttpRequestParams?: any): Observable<PensionerBankAcDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     * @param pensionerBankAcDTO 
     */
    apiV1PpoPpoIdBankAccountsPut(ppoId: number, pensionerBankAcDTO?: PensionerBankAcDTO, extraHttpRequestParams?: any): Observable<PensionerBankAcDTOAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     */
    apiV1PpoPpoIdDetailsGet(ppoId: number, extraHttpRequestParams?: any): Observable<PensionerResponseDTOAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     * @param pensionerEntryDTO 
     */
    apiV1PpoPpoIdDetailsPut(ppoId: number, pensionerEntryDTO?: PensionerEntryDTO, extraHttpRequestParams?: any): Observable<PensionerResponseDTOAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     */
    apiV1PpoPpoIdFirstBillGeneralPost(ppoId: number, extraHttpRequestParams?: any): Observable<PensionerFirstBillResponseDTOJsonAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     * @param statusFlag 
     */
    apiV1PpoPpoIdStatusStatusFlagDelete(ppoId: number, statusFlag: number, extraHttpRequestParams?: any): Observable<PensionStatusDTOAPIResponse>;

    /**
     * 
     * 
     * @param ppoId 
     * @param statusFlag 
     */
    apiV1PpoPpoIdStatusStatusFlagGet(ppoId: number, statusFlag: number, extraHttpRequestParams?: any): Observable<PensionStatusDTOAPIResponse>;

    /**
     * 
     * 
     * @param pensionStatusEntryDTO 
     */
    apiV1PpoStatusPost(pensionStatusEntryDTO?: PensionStatusEntryDTO, extraHttpRequestParams?: any): Observable<PensionStatusEntryDTOAPIResponse>;

}
