/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DynamicListQueryParameters } from '../model/models';
import { PpoComponentRateEntryDTO } from '../model/models';
import { PpoComponentRateResponseDTOIEnumerableDynamicListResultJsonAPIResponse } from '../model/models';
import { PpoComponentRateResponseDTOJsonAPIResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PensionComponentRevisionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param dynamicListQueryParameters 
     */
    apiV1PpoComponentRatePatch(dynamicListQueryParameters?: DynamicListQueryParameters, extraHttpRequestParams?: any): Observable<PpoComponentRateResponseDTOIEnumerableDynamicListResultJsonAPIResponse>;

    /**
     * 
     * 
     * @param ppoComponentRateEntryDTO 
     */
    apiV1PpoComponentRatePost(ppoComponentRateEntryDTO?: PpoComponentRateEntryDTO, extraHttpRequestParams?: any): Observable<PpoComponentRateResponseDTOJsonAPIResponse>;

}
