/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIResponseStatus = 1 | 2 | 3 | 4;

export const APIResponseStatus = {
    NUMBER_1: 1 as APIResponseStatus,
    NUMBER_2: 2 as APIResponseStatus,
    NUMBER_3: 3 as APIResponseStatus,
    NUMBER_4: 4 as APIResponseStatus
};

