/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BeneficiaryDetailsDTO { 
    beneficiaryName?: string | null;
    beneficiaryCode?: string | null;
    ifscCode?: string | null;
    bankName?: string | null;
    accountNumber?: string | null;
    eMail?: string | null;
    contactNo?: string | null;
    amount?: number | null;
    payeeType?: string | null;
}

