/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HOAChain } from './hOAChain';


export interface BillsListDTO { 
    billId?: number;
    referenceNo?: string | null;
    ddoCode?: string | null;
    ddoDesignation?: string | null;
    billNo?: string | null;
    billDate?: string | null;
    grossAmount?: number | null;
    netAmount?: number | null;
    hoaChain?: HOAChain;
}

