/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BillObjections } from './billObjections';
import { OverruledObjection } from './overruledObjection';


export interface BillCheckingDto { 
    tokenId?: number;
    referenceNo?: string | null;
    billObjections?: BillObjections;
    overruledObjections?: Array<OverruledObjection> | null;
}

