/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateOnly } from './dateOnly';
import { HOAChain } from './hOAChain';
import { SubDeatilsHeadDto } from './subDeatilsHeadDto';


export interface BillDetailsDetailsByRef { 
    ddoCode?: string | null;
    referenceNo?: string | null;
    billNo?: string | null;
    billDate?: DateOnly;
    billType?: number | null;
    billSubType?: string | null;
    ddoDesignation?: string | null;
    payeeDepartment?: string | null;
    hoaChain?: HOAChain;
    subDeatilsHead?: Array<SubDeatilsHeadDto> | null;
    subDeatilsTotalAmount?: number;
    transferAmount?: number | null;
    grossAmount?: number | null;
    netAmount?: number | null;
    agBTAmount?: number | null;
    treasuryBTAmount?: number | null;
    totalBTAmount?: number | null;
    sanctionNo?: number | null;
    sanctionDate?: DateOnly;
}

