/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChequeListDTO { 
    id?: number | null;
    treasurieCode?: string | null;
    micrCode?: string | null;
    series?: string | null;
    start?: number;
    end?: number;
    quantity?: number;
    availableQuantity?: number;
}

