/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChequeInvoiceListDTO { 
    id?: number;
    invoiceDate?: string | null;
    invoiceNumber?: string | null;
    memoNumber?: string | null;
    quantity?: number | null;
    currentStatus?: string | null;
    currentStatusId?: number | null;
}

