/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChequeReceivedDamagedDetailsDTO } from './chequeReceivedDamagedDetailsDTO';


export interface ChequeReceivedDTO { 
    invoiceId?: number;
    status?: number;
    treasuryCode?: string | null;
    micrCode?: string | null;
    series?: string | null;
    chequeReceivedDamagedDetails?: Array<ChequeReceivedDamagedDetailsDTO> | null;
}

