/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChequeIndentListDTO { 
    id?: number;
    indentId?: number | null;
    indentDate?: string | null;
    memoNo?: string | null;
    memoDate?: string | null;
    chequeType?: string | null;
    micrCode?: string | null;
    quantity?: number | null;
    remarks?: string | null;
    currentStatus?: string | null;
    currentStatusId?: number | null;
}

