/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChequeReceivedDataWithMICRDTO { 
    id?: number;
    invoiceId?: number | null;
    invoiceDeatilsId?: number | null;
    start?: number | null;
    end?: number | null;
    micrCode?: string | null;
    quantity?: number | null;
    series?: string | null;
}

