/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DiscountDetailsDTO { 
    discountId?: number;
    denominationFrom?: number;
    denominationTo?: number;
    discount?: number;
    vendorType?: string | null;
    stampCategory?: string | null;
    isActive?: boolean | null;
    createdAt?: number | null;
    createdBy?: number | null;
}

