/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './api-response-status';
import { InitiateFirstPensionBillResponseDTO } from './initiate-first-pension-bill-response-dto';


export interface InitiateFirstPensionBillResponseDTOJsonAPIResponse { 
    result?: InitiateFirstPensionBillResponseDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace InitiateFirstPensionBillResponseDTOJsonAPIResponse {
}


