/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PensionerBankAcDTO } from './pensioner-bank-ac-dto';
import { DateOnly } from './date-only';
import { PpoPaymentListItemDTO } from './ppo-payment-list-item-dto';
import { PensionerListItemDTO } from './pensioner-list-item-dto';
import { PensionCategoryResponseDTO } from './pension-category-response-dto';


export interface InitiateFirstPensionBillResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    pensioner: PensionerListItemDTO;
    bankAccount: PensionerBankAcDTO;
    pensionCategory: PensionCategoryResponseDTO;
    pensionerPayments: Array<PpoPaymentListItemDTO>;
    billGeneratedUptoDate: DateOnly;
    billId?: number;
    billDate?: DateOnly;
    treasuryVoucherNo?: string | null;
    treasuryVoucherId?: number;
    treasuryVoucherDate?: DateOnly;
    grossAmount?: number;
    netAmount?: number;
}

