/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateOnly } from './dateOnly';
import { HOAChain } from './hOAChain';


export interface PayMandateShortListDTO { 
    tokenId?: number;
    tokenDate?: DateOnly;
    billNo?: string | null;
    billDate?: DateOnly;
    trFormats?: string | null;
    billTypes?: string | null;
    billModule?: string | null;
    billPeriod?: string | null;
    noOfBeneficiarie?: number | null;
    neAmount?: number | null;
    ecsAmount?: number | null;
    chequeAmount?: number | null;
    detailHead?: string | null;
    headOfAccounts?: HOAChain;
    ddoCode?: string | null;
}

