/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PensionStatusEntryDTO } from './pension-status-entry-dto';
import { APIResponseStatus } from './api-response-status';


export interface PensionStatusEntryDTOAPIResponse { 
    result?: PensionStatusEntryDTO;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace PensionStatusEntryDTOAPIResponse {
}


