/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PensionerBankAcDTO } from './pensionerBankAcDTO';
import { PpoPaymentListItemDTO } from './ppoPaymentListItemDTO';
import { PensionerListItemDTO } from './pensionerListItemDTO';
import { PensionCategoryResponseDTO } from './pensionCategoryResponseDTO';


export interface PensionerFirstBillResponseDTO { 
    dataSource?: { [key: string]: any; } | null;
    pensioner: PensionerListItemDTO;
    bankAccount: PensionerBankAcDTO;
    pensionCategory: PensionCategoryResponseDTO;
    pensionerPayments: Array<PpoPaymentListItemDTO>;
}

