/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIResponseStatus } from './aPIResponseStatus';
import { StampCategoryDTO } from './stampCategoryDTO';


export interface StampCategoryDTOIEnumerableAPIResponse { 
    result?: Array<StampCategoryDTO> | null;
    apiResponseStatus?: APIResponseStatus;
    message?: string | null;
}
export namespace StampCategoryDTOIEnumerableAPIResponse {
}


