/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StampRequisitionInsertDTO { 
    vendorId?: number;
    sheet?: number;
    label?: number;
    combinationId?: number;
    requisitionDate?: number | null;
    requisitionNo?: string | null;
    challanAmount?: number;
    raisedToTreasury?: string | null;
}

