/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StampVendorDetailsDropdownDTO { 
    stampVendorId?: number;
    vendorName?: string | null;
    vendorTypeId?: number | null;
    vendorType?: string | null;
    vendorTreasury?: string | null;
    licenseNo?: string | null;
    phoneNumber?: number | null;
    panNumber?: string | null;
}

