/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StampIndentInsertDTO { 
    stampCombinationId?: number;
    memoNumber: string;
    memoDate: number;
    remarks: string;
    sheet: number;
    label: number;
    quantity: number;
    amount: number;
    raisedToTreasuryCode: string;
}

