/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StampCategoryDTO { 
    stampCategory1?: string | null;
    description?: string | null;
    isActive?: boolean | null;
    createdAt?: number | null;
    createdBy?: number | null;
    updatedAt?: number | null;
    updatedBy?: number | null;
    stampCategoryId?: number;
}

