/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StampVendorDTO { 
    vendorName?: string | null;
    vendorType?: string | null;
    stampVendorId?: number;
    licenseNo?: string | null;
    address?: string | null;
    phoneNumber?: number | null;
    vendorTreasury?: string | null;
    effectiveFrom?: string | null;
    validUpto?: string | null;
    panNumber?: string | null;
    isActive?: boolean | null;
    activeAtGrips?: boolean | null;
    vendorPhoto?: string | null;
    vendorPanPhoto?: string | null;
    vendorLicencePhoto?: string | null;
    createdAt?: number | null;
    createdBy?: number | null;
    updatedAt?: number | null;
    updatedBy?: number | null;
}

