/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StampCombinationDTO { 
    stampCombinationId?: number;
    stampCategory1?: string | null;
    stampCategoryId?: number;
    description?: string | null;
    denomination?: number;
    stampDenominationId?: number;
    noLabelPerSheet?: number;
    stampLabelId?: number;
    isActive?: boolean;
    createdAt?: number | null;
    createdBy?: number | null;
}

