/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StampIndentDTO { 
    stampIndentId?: number;
    memoNumber?: string | null;
    memoDate?: number;
    remarks?: string | null;
    raisedToTreasuryCode?: string | null;
    raisedByTreasuryCode?: string | null;
    stmapCategory?: string | null;
    description?: string | null;
    denomination?: number;
    labelPerSheet?: number;
    sheet?: number;
    label?: number;
    quantity?: number;
    amount?: number;
    createdAt?: number;
    createdBy?: number;
    status?: string | null;
}

