/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenWithObjectionDto { 
    id?: number;
    toeknId?: number;
    objectionDescription?: string | null;
    objectionId?: number | null;
    objectionBy?: number | null;
    objectionType?: string | null;
    objectionRemark?: string | null;
    isOverruled?: boolean | null;
    overruledBy?: string | null;
}

