/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateOnly } from './dateOnly';


export interface TokenList { 
    tokenId?: number;
    tokenNumberr?: number;
    tokenDate?: DateOnly;
    financialYear?: string | null;
    referenceNo?: string | null;
    currentStatus?: string | null;
    currentStatusSlug?: string | null;
    currentStatusId?: number | null;
    ddoCode?: string | null;
}

