/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateOnly } from './dateOnly';
import { HOAChain } from './hOAChain';


export interface TokenPrintDTO { 
    tokenNumber?: number;
    tokenDate?: DateOnly;
    billNo?: string | null;
    billDate?: DateOnly;
    ddoCode?: string | null;
    payeeDept?: string | null;
    hoaChain?: HOAChain;
    grossAmount?: number | null;
    netAmount?: number | null;
}

