/**
 * CTS-BE
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListHeader } from './listHeader';
import { TokenList } from './tokenList';


export interface TokenListIEnumerableDynamicListResult { 
    headers?: Array<ListHeader> | null;
    data?: Array<TokenList> | null;
    dataCount?: number;
}

