import { Injectable } from '@angular/core';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

@Injectable({
  providedIn: 'root'
})
export class FileGenerationBillPrintService {
  constructor() { }

  generatePdf(reportData: any): void {
    const doc = new jsPDF();

    const addHeader = (startY: number) => {
      doc.setFontSize(15);
      doc.text('Govt. of West Bengal - Treasury', 65, startY);
      doc.setFontSize(12);
      doc.text('Malda-I', 95, startY + 5);
      doc.setFontSize(10);
      doc.text('Bill for the Month of April 2024', 79, startY + 10);
      doc.text('For the Period of 01/04/2024 To 30/04/2024', 69, startY + 15);

      // Add underline
      doc.line(10, startY + 20, 200, startY + 20);

      doc.text(`Bank: ${reportData.bank}`, 10, startY + 30);
      doc.text('Head of Account: 2017-01-105-001-00-V-04', 130, startY + 30);
      doc.text(`Category: ${reportData.category}`, 10, startY + 35);
      doc.text(`Bill Date: 29/04/2024`, 130, startY + 35);
      doc.text(`Voucher Date: 30/04/2024`, 10, startY + 40);
      doc.text(`Bill Number: ${reportData.billNumber}`, 170, startY + 35);
      doc.text(`Voucher Number: ${reportData.voucherNumber}`, 150, startY + 40);
    };

    const addTable = (startY: number, data: any[], addTotalRow: boolean) => {
      const columns = ["Sl No", "PPO ID", "Pensioner Name", "Bank A/C No", "Total Payable", "Basic Pension", "DR", "MR", "Commuted Amount", "Overdrawal", "DP", "Additional Pension", "Arrear", "IR", "By-Transfer"];
      const rows = data.map((item: any, index: number) => [
        index + 1,
        item.ppoId,
        item.pensionerName,
        item.bankAccountNo,
        item.totalPayable,
        item.basicPension,
        item.dr,
        item.mr,
        item.commutedAmount,
        item.overdrawal,
        item.dp,
        item.additionalPension,
        item.arrear,
        item.ir,
        item.byTransfer,
      ]);

      if (addTotalRow) {
        rows.push([
          '', '', 'Account Head Wise Total', '', 
          reportData.total, '', '', '', '', '', '', '', '', '', ''
        ]);
      }

      // Add the table
      (doc as any).autoTable({
        head: [columns],
        body: rows,
        startY: startY,
        theme: 'grid',
        styles: { fontSize: 8, cellPadding: 1 },
        headStyles: { fillColor: [100, 100, 100] },
      });

      return (doc as any).lastAutoTable.finalY + 10;
    };

    // Add header and table twice
    addHeader(10);
    let finalY = addTable(55, reportData.details, true);

    addHeader(finalY + 20);
    finalY = addTable(finalY + 65, [], true); // Adding only table headers for the second section

    // Add footer details
    doc.text('Bill Gross Rs. :', 10, finalY);
    doc.text(reportData.netAmount, 50, finalY);
    doc.text('Net Amount:', 70, finalY);
    doc.text(reportData.netAmount, 100, finalY);
    doc.text(`Pay Rs. :`, 10, finalY + 10);
    doc.text(reportData.payAmount, 50, finalY + 10);
    doc.text('Rupees (in words):', 70, finalY+10);
    doc.text(reportData.amountInWords, 100, finalY+10);
    doc.text('By-Transfer Credit Rs. 0', 10, finalY + 20);

    // Add instructions
    doc.setFontSize(10);
    doc.text('INSTRUCTIONS', 60, finalY + 30);
    const instructions = [
      '1. The Pensioner\'s Single / Joint named account with the family pensioner will be operated for drawal of pension only.',
      '2. In the event of the death of the Pensioner, the Bank will intimate the actual date of death of the pensioner and the Bank will not release the Balance in the account of the Pensioner unless clearance is received from Treasury.',
      '3. If the pension has remained undrawn for six months the Bank will send an intimation to that effect to the Treasury.'
    ];
    doc.text(instructions.join('\n'), 10, finalY + 40);

    // Signature lines
    doc.text('T.O. / A.T.O', 170, finalY + 80);
    doc.text('Generated by SOURAV DEY', 10, finalY + 90);
    doc.text('Date: 23 July 2024', 10, finalY + 100);

    // Save the PDF
    doc.save('bill-report.pdf');
  }
}
