export enum Status {
    "FORWARDED TO SUPERINTENDENT" = 10,
    "FORWARDED TO TREASURY OFFICER" = 11,
    "REJECTED BY TREASURY OFFICER" = 12,
    "APPROVED BY TREASURY OFFICER" = 13,
    "APPROVED BY SUPERINTENDENT" = 15,
    "REJECTED BY SUPERINTENDENT" = 16
  }