export enum Status {
    "FORWARDED TO SUPERINTENDENT" = 10,
    "APPROVED BY SUPERINTENDENT" = 15,
    "REJECTED BY SUPERINTENDENT" = 16,

    "FORWARDED TO TREASURY OFFICER" = 11,
    "APPROVED BY TREASURY OFFICER" = 12,
    "REJECTED BY TREASURY OFFICER" = 13,

    "RECEIVED BY TREASURY OFFICER" = 14
  }