export interface PPOEntryINF {
    "ppoId": string,
    "ppoNo": string,
    "ppoType": 'P' | 'F' | 'C',
    "psaType": 'A' | 'D' | 'O',
    "ppoSubType": string,
    "ppoCategory": string,
    "ppoSubCategory": string,
    "pensionerName": string,
    "dateOfBirth": string,
    "gender": 'M' | 'F' | 'O',
    "mobileNumber": string,
    "emailId": string,
    "pensionerAddress":string,
    "identificationMark": 'S' | 'N',
    "panNo": string,
    "aadhaarNo": string,
    "dateOfRetirement": string,
    "dateOfCommencement": string,
    "basicPensionAmount": number,
    "commutedPensionAmount": string,
    "enhancePensionAmount": string,
    "reducedPensionAmount": string,
    "religion": 'H' | 'M' | 'O'
}